### ISSUE TITLE
Error when setting version attribute

### ISSUE THREAD

**Issue by dpnl87** [Icinga/chef-icinga2#261]
When locking the version in my wrapper cookbook I get the following error I can't seem to get fixed.

If I construct the `web_version` mysql I get '2.4.1-1' as expected.
```
node.default['icinga2']['web2']['enable'] = true
node.default['icinga2']['web2']['version']['icingaweb2'] = '2.4.1'
node.default['icinga2']['web2']['version']['icingacli'] = '2.4.1'
```

```
NoMethodError
-------------
Undefined node attribute or method `+' on `node'

Cookbook Trace:
---------------
  /var/chef/cache/cookbooks/icinga2/recipes/server_web2.rb:21:in `from_file'
  /var/chef/cache/cookbooks/icinga2/recipes/server.rb:46:in `from_file'
  /var/chef/cache/cookbooks/valtechnl_icinga/recipes/server.rb:17:in `from_file'
  /var/chef/cache/cookbooks/valtechnl_icinga/recipes/default.rb:7:in `from_file'

Relevant File Content:
----------------------
/var/chef/cache/cookbooks/icinga2/recipes/server_web2.rb:

 14:  # Unless required by applicable law or agreed to in writing, software
 15:  # distributed under the License is distributed on an "AS IS" BASIS,
 16:  # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 17:  # See the License for the specific language governing permissions and
 18:  # limitations under the License.
 19:  #
 20:
 21>> web2_version = node['icinga2']['web2']['install_method'] == 'source' ? 'v' + node['icinga2']['web2']['version'] : node['icinga2']['web2']['version'] + '-' + node['icinga2']['web2']['release'] + node['icinga2']['icinga2_version_suffix'].to_s
 22:  cli_version = node['icinga2']['web2']['version'] + '-' + node['icinga2']['web2']['release'] + node['icinga2']['icinga2_version_suffix']
 23:
 24:  puts web2_version
 25:
 26:  directory node['icinga2']['web2']['conf_dir'] do
 27:    owner node[node['icinga2']['web_engine']]['user']
 28:    group node[node['icinga2']['web_engine']]['group']
 29:    mode '02770'
 30:  end

```

**Comment by vkhatri** [comment]
@dpnl87 Could you please perform upstream pull and retry?

**Comment by dpnl87** [comment]
@vkhatri I'm running on master for this repo. Not really sure what you mean with upstream?

**Comment by vkhatri** [comment]
Sorry for the confusion, I meant to say pull `master` branch. 

Current `master` branch has simplified attributes.

https://github.com/Icinga/chef-icinga2/blob/master/attributes/server_web2.rb#L6

```ruby
default['icinga2']['web2']['version']['icingaweb2'] = '2.4.1-1'
default['icinga2']['web2']['version']['icingacli'] = '2.4.1-1'
```

https://github.com/Icinga/chef-icinga2/blob/master/recipes/server_web2.rb#L22 :

```ruby
cli_package_version = node['icinga2']['web2']['version']['icingacli'] + node['icinga2']['icinga2_version_suffix']
web2_package_version = node['icinga2']['web2']['version']['icingaweb2'] + node['icinga2']['icinga2_version_suffix']
web2_source_version = 'v' + node['icinga2']['web2']['version']['icingaweb2'].split('-')[0]
```

**Comment by dpnl87** [comment]
I'll do some more testing on a simulated environment. For now I was able to work around this issue by setting `node.default['icinga2']['ignore_version'] = true`

**Comment by vkhatri** [comment]
Closing as the issue was fixed.
