### ISSUE TITLE
Installing icinga2 on CentOS fails

### ISSUE THREAD

**Issue by wndhydrnt** [Icinga/chef-icinga2#302]
## Expected Behavior
It should be possible to install the icinga2 package.

## Current Behavior
Installation errors due to yum not able to find a required package.

## Steps to Reproduce (for bugs)
Include `icinga2::server` in your run.

## Context
Here is the log output of a kitchen run:

```
* yum_package[icinga2] action install

================================================================================
Error executing action `install` on resource 'yum_package[icinga2]'
================================================================================

Chef::Exceptions::Exec
----------------------
yum -d0 -e0 -y install icinga2-2.6.1-1.el7.centos returned 1:
STDOUT:  You could try using --skip-broken to work around the problem
You could try running: rpm -Va --nofiles --nodigest

STDERR: Error: Package: icinga2-bin-2.6.1-1.el7.centos.x86_64 (icinga2)
   Requires: libsocketpair.so.2.6.1()(64bit)
   Available: icinga2-libs-2.6.1-1.el7.centos.x86_64 (icinga2)
       libsocketpair.so.2.6.1()(64bit)
   Available: icinga2-libs-2.5.0-1.el7.centos.x86_64 (icinga2)
       Not found
   Available: icinga2-libs-2.5.0-2.el7.centos.x86_64 (icinga2)
       Not found
   Available: icinga2-libs-2.5.0-3.el7.centos.x86_64 (icinga2)
       Not found
   Available: icinga2-libs-2.5.1-1.el7.centos.x86_64 (icinga2)
       Not found
   Available: icinga2-libs-2.5.2-1.el7.centos.x86_64 (icinga2)
       Not found
   Available: icinga2-libs-2.5.3-1.el7.centos.x86_64 (icinga2)
       Not found
   Available: icinga2-libs-2.5.4-1.el7.centos.x86_64 (icinga2)
       Not found
   Available: icinga2-libs-2.6.0-1.el7.centos.x86_64 (icinga2)
      ~libsocketpair.so.2.6.0()(64bit)
   Available: icinga2-libs-2.6.2-1.el7.centos.x86_64 (icinga2)
      ~libsocketpair.so.2.6.2()(64bit)
   Available: icinga2-libs-2.6.3-1.el7.centos.x86_64 (icinga2)
      ~libsocketpair.so.2.6.3()(64bit)
   Installing: icinga2-libs-2.7.0-1.el7.icinga.x86_64 (icinga2)
      ~libsocketpair.so.2.7.0()(64bit)
Error: Package: icinga2-bin-2.6.1-1.el7.centos.x86_64 (icinga2)
   Requires: libconfig.so.2.6.1()(64bit)
   Available: icinga2-libs-2.6.1-1.el7.centos.x86_64 (icinga2)
       libconfig.so.2.6.1()(64bit)
   Available: icinga2-libs-2.5.0-1.el7.centos.x86_64 (icinga2)
       Not found
   Available: icinga2-libs-2.5.0-2.el7.centos.x86_64 (icinga2)
       Not found
   Available: icinga2-libs-2.5.0-3.el7.centos.x86_64 (icinga2)
       Not found
   Available: icinga2-libs-2.5.1-1.el7.centos.x86_64 (icinga2)
       Not found
   Available: icinga2-libs-2.5.2-1.el7.centos.x86_64 (icinga2)
       Not found
   Available: icinga2-libs-2.5.3-1.el7.centos.x86_64 (icinga2)
       Not found
   Available: icinga2-libs-2.5.4-1.el7.centos.x86_64 (icinga2)
       Not found
   Available: icinga2-libs-2.6.0-1.el7.centos.x86_64 (icinga2)
      ~libconfig.so.2.6.0()(64bit)
   Available: icinga2-libs-2.6.2-1.el7.centos.x86_64 (icinga2)
      ~libconfig.so.2.6.2()(64bit)
   Available: icinga2-libs-2.6.3-1.el7.centos.x86_64 (icinga2)
      ~libconfig.so.2.6.3()(64bit)
   Installing: icinga2-libs-2.7.0-1.el7.icinga.x86_64 (icinga2)
      ~libconfig.so.2.7.0()(64bit)
Error: Package: icinga2-bin-2.6.1-1.el7.centos.x86_64 (icinga2)
   Requires: libexecvpe.so.2.6.1()(64bit)
   Available: icinga2-libs-2.6.1-1.el7.centos.x86_64 (icinga2)
       libexecvpe.so.2.6.1()(64bit)
   Available: icinga2-libs-2.5.0-1.el7.centos.x86_64 (icinga2)
       Not found
   Available: icinga2-libs-2.5.0-2.el7.centos.x86_64 (icinga2)
       Not found
   Available: icinga2-libs-2.5.0-3.el7.centos.x86_64 (icinga2)
       Not found
   Available: icinga2-libs-2.5.1-1.el7.centos.x86_64 (icinga2)
       Not found
   Available: icinga2-libs-2.5.2-1.el7.centos.x86_64 (icinga2)
       Not found
   Available: icinga2-libs-2.5.3-1.el7.centos.x86_64 (icinga2)
       Not found
   Available: icinga2-libs-2.5.4-1.el7.centos.x86_64 (icinga2)
       Not found
   Available: icinga2-libs-2.6.0-1.el7.centos.x86_64 (icinga2)
      ~libexecvpe.so.2.6.0()(64bit)
   Available: icinga2-libs-2.6.2-1.el7.centos.x86_64 (icinga2)
      ~libexecvpe.so.2.6.2()(64bit)
   Available: icinga2-libs-2.6.3-1.el7.centos.x86_64 (icinga2)
      ~libexecvpe.so.2.6.3()(64bit)
   Installing: icinga2-libs-2.7.0-1.el7.icinga.x86_64 (icinga2)
      ~libexecvpe.so.2.7.0()(64bit)
Error: Package: icinga2-bin-2.6.1-1.el7.centos.x86_64 (icinga2)
   Requires: icinga2-libs = 2.6.1-1.el7.centos
   Available: icinga2-libs-2.5.0-1.el7.centos.x86_64 (icinga2)
       icinga2-libs = 2.5.0-1.el7.centos
   Available: icinga2-libs-2.5.0-2.el7.centos.x86_64 (icinga2)
       icinga2-libs = 2.5.0-2.el7.centos
   Available: icinga2-libs-2.5.0-3.el7.centos.x86_64 (icinga2)
       icinga2-libs = 2.5.0-3.el7.centos
   Available: icinga2-libs-2.5.1-1.el7.centos.x86_64 (icinga2)
       icinga2-libs = 2.5.1-1.el7.centos
   Available: icinga2-libs-2.5.2-1.el7.centos.x86_64 (icinga2)
       icinga2-libs = 2.5.2-1.el7.centos
   Available: icinga2-libs-2.5.3-1.el7.centos.x86_64 (icinga2)
       icinga2-libs = 2.5.3-1.el7.centos
   Available: icinga2-libs-2.5.4-1.el7.centos.x86_64 (icinga2)
       icinga2-libs = 2.5.4-1.el7.centos
   Available: icinga2-libs-2.6.0-1.el7.centos.x86_64 (icinga2)
       icinga2-libs = 2.6.0-1.el7.centos
   Available: icinga2-libs-2.6.1-1.el7.centos.x86_64 (icinga2)
       icinga2-libs = 2.6.1-1.el7.centos
   Available: icinga2-libs-2.6.2-1.el7.centos.x86_64 (icinga2)
       icinga2-libs = 2.6.2-1.el7.centos
   Available: icinga2-libs-2.6.3-1.el7.centos.x86_64 (icinga2)
       icinga2-libs = 2.6.3-1.el7.centos
   Installing: icinga2-libs-2.7.0-1.el7.icinga.x86_64 (icinga2)
       icinga2-libs = 2.7.0-1.el7.icinga
Error: Package: icinga2-bin-2.6.1-1.el7.centos.x86_64 (icinga2)
   Requires: libmmatch.so.2.6.1()(64bit)
   Available: icinga2-libs-2.6.1-1.el7.centos.x86_64 (icinga2)
       libmmatch.so.2.6.1()(64bit)
   Available: icinga2-libs-2.5.0-1.el7.centos.x86_64 (icinga2)
       Not found
   Available: icinga2-libs-2.5.0-2.el7.centos.x86_64 (icinga2)
       Not found
   Available: icinga2-libs-2.5.0-3.el7.centos.x86_64 (icinga2)
       Not found
   Available: icinga2-libs-2.5.1-1.el7.centos.x86_64 (icinga2)
       Not found
   Available: icinga2-libs-2.5.2-1.el7.centos.x86_64 (icinga2)
       Not found
   Available: icinga2-libs-2.5.3-1.el7.centos.x86_64 (icinga2)
       Not found
   Available: icinga2-libs-2.5.4-1.el7.centos.x86_64 (icinga2)
       Not found
   Available: icinga2-libs-2.6.0-1.el7.centos.x86_64 (icinga2)
      ~libmmatch.so.2.6.0()(64bit)
   Available: icinga2-libs-2.6.2-1.el7.centos.x86_64 (icinga2)
      ~libmmatch.so.2.6.2()(64bit)
   Available: icinga2-libs-2.6.3-1.el7.centos.x86_64 (icinga2)
      ~libmmatch.so.2.6.3()(64bit)
   Installing: icinga2-libs-2.7.0-1.el7.icinga.x86_64 (icinga2)
      ~libmmatch.so.2.7.0()(64bit)
Error: Package: icinga2-bin-2.6.1-1.el7.centos.x86_64 (icinga2)
   Requires: libcli.so.2.6.1()(64bit)
   Available: icinga2-libs-2.6.1-1.el7.centos.x86_64 (icinga2)
       libcli.so.2.6.1()(64bit)
   Available: icinga2-libs-2.5.0-1.el7.centos.x86_64 (icinga2)
       Not found
   Available: icinga2-libs-2.5.0-2.el7.centos.x86_64 (icinga2)
       Not found
   Available: icinga2-libs-2.5.0-3.el7.centos.x86_64 (icinga2)
       Not found
   Available: icinga2-libs-2.5.1-1.el7.centos.x86_64 (icinga2)
       Not found
   Available: icinga2-libs-2.5.2-1.el7.centos.x86_64 (icinga2)
       Not found
   Available: icinga2-libs-2.5.3-1.el7.centos.x86_64 (icinga2)
       Not found
   Available: icinga2-libs-2.5.4-1.el7.centos.x86_64 (icinga2)
       Not found
   Available: icinga2-libs-2.6.0-1.el7.centos.x86_64 (icinga2)
      ~libcli.so.2.6.0()(64bit)
   Available: icinga2-libs-2.6.2-1.el7.centos.x86_64 (icinga2)
      ~libcli.so.2.6.2()(64bit)
   Available: icinga2-libs-2.6.3-1.el7.centos.x86_64 (icinga2)
      ~libcli.so.2.6.3()(64bit)
   Installing: icinga2-libs-2.7.0-1.el7.icinga.x86_64 (icinga2)
      ~libcli.so.2.7.0()(64bit)
Error: Package: icinga2-bin-2.6.1-1.el7.centos.x86_64 (icinga2)
   Requires: libremote.so.2.6.1()(64bit)
   Available: icinga2-libs-2.6.1-1.el7.centos.x86_64 (icinga2)
       libremote.so.2.6.1()(64bit)
   Available: icinga2-libs-2.5.0-1.el7.centos.x86_64 (icinga2)
       Not found
   Available: icinga2-libs-2.5.0-2.el7.centos.x86_64 (icinga2)
       Not found
   Available: icinga2-libs-2.5.0-3.el7.centos.x86_64 (icinga2)
       Not found
   Available: icinga2-libs-2.5.1-1.el7.centos.x86_64 (icinga2)
       Not found
   Available: icinga2-libs-2.5.2-1.el7.centos.x86_64 (icinga2)
       Not found
   Available: icinga2-libs-2.5.3-1.el7.centos.x86_64 (icinga2)
       Not found
   Available: icinga2-libs-2.5.4-1.el7.centos.x86_64 (icinga2)
       Not found
   Available: icinga2-libs-2.6.0-1.el7.centos.x86_64 (icinga2)
      ~libremote.so.2.6.0()(64bit)
   Available: icinga2-libs-2.6.2-1.el7.centos.x86_64 (icinga2)
      ~libremote.so.2.6.2()(64bit)
   Available: icinga2-libs-2.6.3-1.el7.centos.x86_64 (icinga2)
      ~libremote.so.2.6.3()(64bit)
   Installing: icinga2-libs-2.7.0-1.el7.icinga.x86_64 (icinga2)
      ~libremote.so.2.7.0()(64bit)
Error: Package: icinga2-bin-2.6.1-1.el7.centos.x86_64 (icinga2)
   Requires: libbase.so.2.6.1()(64bit)
   Available: icinga2-libs-2.6.1-1.el7.centos.x86_64 (icinga2)
       libbase.so.2.6.1()(64bit)
   Available: icinga2-libs-2.5.0-1.el7.centos.x86_64 (icinga2)
       Not found
   Available: icinga2-libs-2.5.0-2.el7.centos.x86_64 (icinga2)
       Not found
   Available: icinga2-libs-2.5.0-3.el7.centos.x86_64 (icinga2)
       Not found
   Available: icinga2-libs-2.5.1-1.el7.centos.x86_64 (icinga2)
       Not found
   Available: icinga2-libs-2.5.2-1.el7.centos.x86_64 (icinga2)
       Not found
   Available: icinga2-libs-2.5.3-1.el7.centos.x86_64 (icinga2)
       Not found
   Available: icinga2-libs-2.5.4-1.el7.centos.x86_64 (icinga2)
       Not found
   Available: icinga2-libs-2.6.0-1.el7.centos.x86_64 (icinga2)
      ~libbase.so.2.6.0()(64bit)
   Available: icinga2-libs-2.6.2-1.el7.centos.x86_64 (icinga2)
      ~libbase.so.2.6.2()(64bit)
   Available: icinga2-libs-2.6.3-1.el7.centos.x86_64 (icinga2)
      ~libbase.so.2.6.3()(64bit)
   Installing: icinga2-libs-2.7.0-1.el7.icinga.x86_64 (icinga2)
      ~libbase.so.2.7.0()(64bit)

Cookbook Trace:
---------------
/tmp/kitchen/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
/tmp/kitchen/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels) in converge'
/tmp/kitchen/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'
/tmp/kitchen/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in converge'
/tmp/kitchen/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'

Resource Declaration:
---------------------
# In /tmp/kitchen/cookbooks/icinga2/recipes/core_install.rb

47: package 'icinga2' do
48:   version node['icinga2']['version'] + node['icinga2']['icinga2_version_suffix'] unless node['icinga2']['ignore_version']
49:   notifies :restart, 'service[icinga2]', :delayed
50: end

Compiled Resource:
------------------
# Declared in /tmp/kitchen/cookbooks/icinga2/recipes/core_install.rb:47:in `from_file'

yum_package("icinga2") do
 package_name "icinga2"
 action [:install]
 retries 0
 retry_delay 2
 default_guard_interpreter :default
 declared_type :package
 cookbook_name :icinga2
 recipe_name "core_install"
 version "2.6.1-1.el7.centos"
 flush_cache {:before=>false, :after=>false}
end
```

## Your Environment
* Cookbook version (`knife cookbook show icinga2`): 2.9.3
* Chef version (`chef-shell -v`): 12.7.2
* Operating System and version: CentOS 7.2 (Kitchen platform `centos-7.2`)

**Comment by kjbweb** [comment]
I'm hitting this error too, identical environment to yours.

**Comment by vkhatri** [comment]
Will take a look.

**Comment by vkhatri** [comment]
Could you please give a try to `v3.0.0`?

**Comment by kjbweb** [comment]
Nearly, still fails though.

Chef is looking to install the following:

>           yum_package("icinga2") do
>              package_name "icinga2"
>              action [:install]
>              retries 0
>              retry_delay 2
>              default_guard_interpreter :default
>              declared_type :package
>              cookbook_name "icinga2"
>              recipe_name "core_install"
>              flush_cache {:before=>false, :after=>false}
>              version "2.7.0-1.el7.centos"
>            end

Though the following is present within the repo:

> ✓ root@icinga-master-centos-73.vagrantup.com:~# yum info icinga2
> Loaded plugins: fastestmirror
> Loading mirror speeds from cached hostfile
>  * IUS: mirrors.ircam.fr
>  * base: mirrors.melbourne.co.uk
>  * epel: www.mirrorservice.org
>  * extras: mirrors.melbourne.co.uk
>  * updates: mirrors.coreix.net
> Available Packages
> Name        : icinga2
> Arch        : x86_64
> Version     : 2.7.0
> Release     : 1.el7.icinga
> Size        : 9.2 k
> Repo        : icinga2/7
> Summary     : Network monitoring application
> URL         : https://www.icinga.com/
> License     : GPL-2.0+
> Description : Meta package for Icinga 2 Core, DB IDO and Web.

Note `1.el7.icinga` being present in the repo, whilst Chef's looking to install `1.el7.centos`

**Comment by vkhatri** [comment]
Not sure why kitchen did not fail for me earlier. Will take a look shortly.

**Comment by scopenco** [comment]
This is not cookbook problem, it's yum repository problem. You should install the correct repo configuration. Are you installing icinga2 repo from this icinga2 cookbook?

**Comment by dnsmichi** [comment]
I think that the default calculated version suffix is wrong, which attempts to pin the version to a specific package.

https://github.com/Icinga/chef-icinga2/blob/c3a17dffc274bf367e7d1fe0a8dea5be87bb9d4a/attributes/repo.rb#L22

puts `centos` instead of `icinga`. Packages since 2.7.x use the suffix, e.g. `icinga2-2.7.1-1.el7.icinga.x86_64.rpm`.

I don't know much about Chef, but that block should be changed @vkhatri

**Comment by wndhydrnt** [comment]
Changes in version 3.0.0 solved the issue for me. Closing.
